const resList = [
  {
    type: "restaurant",
    data: {
      id: 1,
      name: "Taco Haven",
      cuisine: "Mexican",
      rating: 4.0,
      address: "789 Oak St, Villagetown",
      phone: "(555) 555-5555",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 2,
      name: "Pizza Palace",
      cuisine: "Italian",
      rating: 4.5,
      address: "123 Main St, Downtown",
      phone: "(555) 555-1234",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 3,
      name: "Burger Barn",
      cuisine: "American",
      rating: 3.2,
      address: "456 Elm St, Suburbia",
      phone: "(555) 555-5678",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 4,
      name: "Curry Corner",
      cuisine: "Indian",
      rating: 4.3,
      address: "789 Maple Ave, City Center",
      phone: "(555) 555-7890",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 5,
      name: "Sushi Samba",
      cuisine: "Japanese",
      rating: 3.7,
      address: "567 Pine St, Waterfront",
      phone: "(555) 555-3456",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 6,
      name: "Mamma Mia",
      cuisine: "Italian",
      rating: 4.2,
      address: "321 Cedar St, Hillside",
      phone: "(555) 555-6543",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 7,
      name: "Dragon Wok",
      cuisine: "Chinese",
      rating: 3.1,
      address: "890 Elm St, Chinatown",
      phone: "(555) 555-2345",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 8,
      name: "La Taqueria",
      cuisine: "Mexican",
      rating: 3.4,
      address: "234 Oak St, Downtown",
      phone: "(555) 555-8765",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 9,
      name: "The Steakhouse",
      cuisine: "Steakhouse",
      rating: 4.6,
      address: "456 Pine St, Financial District",
      phone: "(555) 555-4321",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 10,
      name: "Mediterraneo",
      cuisine: "Mediterranean",
      rating: 4.3,
      address: "678 Cedar St, Riverside",
      phone: "(555) 555-2109",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 11,
      name: "Thai Terrace",
      cuisine: "Thai",
      rating: 4.5,
      address: "987 Maple Ave, Parkside",
      phone: "(555) 555-8901",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 12,
      name: "Bistro Boulud",
      cuisine: "French",
      rating: 2.8,
      address: "345 Cedar St, Uptown",
      phone: "(555) 555-1098",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 13,
      name: "Café Istanbul",
      cuisine: "Turkish",
      rating: 2.2,
      address: "543 Elm St, Downtown",
      phone: "(555) 555-7654",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 14,
      name: "BBQ Shack",
      cuisine: "Barbecue",
      rating: 4.6,
      address: "678 Oak St, Suburbia",
      phone: "(555) 555-3210",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 15,
      name: "Vegetarian Delight",
      cuisine: "Vegetarian",
      rating: 4.4,
      address: "234 Pine St, Downtown",
      phone: "(555) 555-6789",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 16,
      name: "Seafood Sensation",
      cuisine: "Seafood",
      rating: 3.7,
      address: "890 Cedar St, Waterfront",
      phone: "(555) 555-4567",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 17,
      name: "The Noodle House",
      cuisine: "Asian",
      rating: 3.3,
      address: "123 Elm St, Chinatown",
      phone: "(555) 555-5432",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 18,
      name: "Fish & Chips",
      cuisine: "British",
      rating: 4.2,
      address: "456 Oak St, Riverside",
      phone: "(555) 555-8765",
      image: "https://via.placeholder.com/150",
    },
  },
  {
    type: "restaurant",
    data: {
      id: 19,
      name: "Greek Taverna",
      cuisine: "Greek",
      rating: 2.5,
      address: "789 Pine St, Hillside",
      phone: "(555) 555-2109",
      image: "https://via.placeholder.com/150",
    },
  },
];

export default resList;
